function TermsPage() {
  return (
    <div className="max-w-screen-2xl lg:w-3/4 w-full mx-auto mt-28 mb-20 px-4 lg:px-10 text-textColor">
      <h1 className="text-3xl font-bold my-6 text-center">
        Terms and Conditions
      </h1>

      <p className="mb-4">
        Welcome to KrishiGyan AI! These Terms and Conditions govern your access
        to and use of our website and all associated services, including data
        analysis, reports, advice, and software features (collectively, the
        "Service").
      </p>

      <p className="mb-4">
        Based on the name, this policy is structured for a service providing
        agricultural knowledge, data, or AI-driven consultation.
      </p>

      <p className="mb-8">
        By accessing, subscribing to, or using the Service, you confirm that you
        have read, understood, and agree to be bound by these Terms and our
        Privacy Policy. If you do not agree with any part of these Terms, you
        must not use the Service.
      </p>

      {/* Section 1 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        1. General Conditions and Service Scope
      </h2>

      <h3 className="text-xl font-medium mb-2">1.1 Eligibility</h3>
      <p className="mb-4">
        By using the Service, you represent that you are at least 18 years of
        age or the age of legal majority in your jurisdiction and are legally
        capable of entering into this agreement.
      </p>

      <h3 className="text-xl font-medium mb-2">1.2 Service Description</h3>
      <p className="mb-4">
        The Service provides digital tools, data analysis, and advisory reports
        related to agriculture, farming, and allied sectors. All content,
        recommendations, and predictions generated by the Service's AI or data
        models are based on specific inputs and historical data.
      </p>

      <h3 className="text-xl font-medium mb-2">
        1.3 Disclaimer of Liability for Advice (Crucial)
      </h3>
      <p className="mb-4">
        You acknowledge that the Service provides information and advisory
        assistance only. We are not liable for crop failure, low yields,
        financial loss, or any damages incurred based on your implementation of
        or reliance on the recommendations, predictions, or reports generated by
        the Service. Farming involves inherent risk, and you assume full
        responsibility for all decisions.
      </p>

      <h3 className="text-xl font-medium mb-2">1.4 Changes to Terms</h3>
      <p className="mb-4">
        We reserve the right to update, change, or replace these Terms at any
        time. Your continued use of the Service after the posting of any changes
        constitutes your acceptance of the new Terms.
      </p>

      {/* Section 2 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        2. User Accounts and Subscriptions
      </h2>

      <h3 className="text-xl font-medium mb-2">
        2.1 Registration and Security
      </h3>
      <p className="mb-4">
        You are responsible for providing true, accurate, and complete
        information during registration. You are responsible for maintaining the
        confidentiality of your password and agree not to share your login
        credentials.
      </p>

      <h3 className="text-xl font-medium mb-2">2.2 Subscriptions and Fees</h3>
      <p className="mb-4">
        Access to premium features, advanced reports, or specialized AI models
        requires payment of subscription fees. You agree to pay all applicable
        fees according to the billing terms specified at the point of purchase.
      </p>

      <h3 className="text-xl font-medium mb-2">2.3 No Guarantee of Refund</h3>
      <p className="mb-4">
        Due to the immediate access to digital reports and software services,
        fees are generally non-refundable. Specific refund terms, if any, will
        be outlined in a separate Refund Policy.
      </p>

      {/* Section 3 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        3. Data Integrity and Input
      </h2>

      <h3 className="text-xl font-medium mb-2">3.1 User Data Responsibility</h3>
      <p className="mb-4">
        You are solely responsible for the accuracy, completeness, and legality
        of all data, input parameters, crop details, soil conditions, and farm
        location information you provide to the Service. The quality of the
        Service's output depends directly on the quality of your input.
      </p>

      <h3 className="text-xl font-medium mb-2">3.2 Data Use License</h3>
      <p className="mb-4">
        By submitting data, you grant The Company a worldwide, royalty-free,
        perpetual license to use and analyze this data (in an anonymized and
        aggregated format) for the purposes of improving the underlying AI
        models, research, and enhancing the overall Service offering. We will
        protect your specific, non-aggregated identity information according to
        our Privacy Policy.
      </p>

      {/* Section 4 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        4. Intellectual Property and Content Use
      </h2>

      <h3 className="text-xl font-medium mb-2">4.1 Company IP</h3>
      <p className="mb-4">
        The Service, its underlying algorithms, AI models, software, user
        interface, branding, and all proprietary reports generated by the system
        are the exclusive property of KrishiGyan AI or its licensors.
      </p>

      <h3 className="text-xl font-medium mb-2">4.2 Use of Reports</h3>
      <p className="mb-4">
        You are granted a limited license to use the reports and data purchased
        or generated specifically for your own internal farming or business
        decision-making. You may not resell, reproduce, or publicly distribute
        the proprietary output of the Service without our express written
        permission.
      </p>

      {/* Section 5 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        5. Prohibited Use and Termination
      </h2>

      <h3 className="text-xl font-medium mb-2">5.1 Prohibited Activities</h3>
      <p className="mb-4">
        You are prohibited from using the Service: (a) for any unlawful or
        fraudulent purpose; (b) to disrupt the functionality or security of the
        platform; (c) to input malicious data; or (d) to attempt to reverse
        engineer the AI models or algorithms.
      </p>

      <h3 className="text-xl font-medium mb-2">5.2 Termination</h3>
      <p className="mb-4">
        We may terminate or suspend your access immediately, without prior
        notice or liability, if you breach these Terms, particularly those
        related to account sharing or prohibited content use.
      </p>

      {/* Section 6 */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">
        6. Governing Law and Contact
      </h2>

      <h3 className="text-xl font-medium mb-2">6.1 Governing Law</h3>
      <p className="mb-4">
        These Terms shall be governed by and construed in accordance with the
        laws of India.
      </p>

      <h3 className="text-xl font-medium mb-2">8. Contact Information</h3>
      <p className="mb-2">
        This website is managed by <strong>LUMINOID TECHNOLOGIES PVT LTD</strong>
      </p>
      <p className="mb-10">
        Questions about these Terms and Conditions should be directed to us at:
        <br /> <strong>Email:</strong> contact@krishigyanai.com
      </p>
    </div>
  );
}

export default TermsPage;
